#!/bin/sh

rm -rf autom4te.cache aclocal.m4 configure make_config
rm -f *~
#exit
# ==================== ON SORT AVANT

here=`pwd`
libdir=salome_adm/unix/config_files
cd $libdir
# Files created by libtoolize
rm -f config.guess config.sub ltmain.sh
# Files created by automake
rm -rf install-sh missing
cd $here
